namespace EBond_API.Models
{
    public class MCAccountModels
    {
        public int        id                              { get; set; }
        public Guid?      iID_MaTam                      { get; set; }
        public string?    AccountID                      { get; set; }
        public string?    CustodyID                      { get; set; }
        public string?    Name                           { get; set; }
        public string?    NameEx                         { get; set; }
        public string?    PasswordHash                   { get; set; }
        public string?    State                          { get; set; }
        public string?    StateVSD                       { get; set; }
        public int?       FunctionID                     { get; set; }
        public string?    StateFunction1                 { get; set; }
        public string?    StateFunctionVSD1              { get; set; }
        public string?    PinCode                        { get; set; }
        public string?    FirstName                      { get; set; }
        public string?    MiddleName                     { get; set; }
        public string?    LastName                       { get; set; }
        public string?    Gender                         { get; set; }
        public DateTime?  dDateOfBirth                   { get; set; }
        public string?    PlaceOfBirth                   { get; set; }
        public string?    IDType                         { get; set; }
        public string?    IDNumber                       { get; set; }
        public string?    IDIssuePlace                   { get; set; }
        public DateTime?  dIDIssueDate                   { get; set; }
        public DateTime?  dIDExpiryDate                  { get; set; }
        public string?    IDFrontFilename                { get; set; }
        public string?    IDBackFilename                 { get; set; }
        public string?    SignatureFilename               { get; set; }
        public string?    AccountTypeID                  { get; set; }
        public string?    AccountClassID                 { get; set; }
        public string?    CalculationMethodID            { get; set; }
        public string?    BranchID                       { get; set; }
        public string?    Introducer                     { get; set; }
        public string?    AEID                           { get; set; }
        public string?    Address                        { get; set; }
        public string?    Address1                       { get; set; }
        public string?    Address2                       { get; set; }
        public string?    Address3                       { get; set; }
        public string?    AddressType                    { get; set; }
        public string?    City                           { get; set; }
        public DateTime?  RegistryDate                   { get; set; }
        public string?    TradingCode                    { get; set; }
        public DateTime?  dTradingDate                   { get; set; }
        public string?    CountryID                      { get; set; }
        public string?    FaxNumber                      { get; set; }
        public string?    SMSNumber                      { get; set; }
        public string?    PhoneNumber                    { get; set; }
        public string?    PhoneType                      { get; set; }
        public string?    EmailAddress                   { get; set; }
        public string?    ReferType                      { get; set; }
        public string?    ReferBy                        { get; set; }
        public DateTime?  ReferExpiryDate                { get; set; }
        public string?    RebateSchemeID                 { get; set; }
        public decimal?   MarginPercentageMultiplier     { get; set; }
        public decimal?   MarginLimit                    { get; set; }
        public decimal?   MarginWarningMultiplier        { get; set; }
        public decimal?   MarginCallMultiplier           { get; set; }
        public decimal?   MarginForcedSellMultiplier     { get; set; }
        public decimal?   ExpensiveInterestRateMultiplie { get; set; }
        public decimal?   OverallMarginPercentage        { get; set; }
        public DateTime?  MarginRenewDate                { get; set; }
        public string?    MarginBank                     { get; set; }
        public string?    MarginContractNumber           { get; set; }
        public string?    MarginRenewFlag                { get; set; }
        public string?    MarginRenewNotifiedFlag        { get; set; }
        public DateTime?  MarginRenewNotifiedTime        { get; set; }
        public decimal?   MarginBLimit                   { get; set; }
        public string?    PhoneCode                      { get; set; }
        public decimal?   TradingLimit                   { get; set; }
        public decimal?   TradingLimitEx                 { get; set; }
        public decimal?   SingleOrderLimit               { get; set; }
        public decimal?   SingleOrderLimitEx             { get; set; }
        public string?    InformationPackageID           { get; set; }
        public string?    RelatedAccountGroup            { get; set; }
        public string?    StaffRelatedAccountFlag        { get; set; }
        public string?    HouseAccountFlag               { get; set; }
        public string?    Remark                         { get; set; }
        public DateTime?  dOpenDate                      { get; set; }
        public DateTime?  EffectiveDate                  { get; set; }
        public DateTime?  dCloseDate                     { get; set; }
        public DateTime?  SuspendDate                    { get; set; }
        public DateTime?  LastTransactionDate            { get; set; }
        public DateTime?  LastDailyStatementDate         { get; set; }
        public DateTime?  LastMonthlyStatementDate       { get; set; }
        public decimal?   MaximumAvailableBalance        { get; set; }
        public decimal?   AvailableBalance               { get; set; }
        public decimal?   MarketValue                    { get; set; }
        public decimal?   MarginValue                    { get; set; }
        public decimal?   AcceptedMarginValue            { get; set; }
        public decimal?   MarginPosition                 { get; set; }
        public decimal?   AssetBalance                   { get; set; }
        public decimal?   LiabilityBalance               { get; set; }
        public decimal?   MarginDebitRatio               { get; set; }
        public decimal?   MarginEquityRatio              { get; set; }
        public decimal?   AssetToDebtRatio               { get; set; }
        public decimal?   MaintenanceMarginRatio         { get; set; }
        public decimal?   CallForDeposit                 { get; set; }
        public DateTime?  CallForDepositDate             { get; set; }
        public int?       CallForDepositDays             { get; set; }
        public DateTime?  MarginLoanStartDate            { get; set; }
        public string?    AllowLendingFlag               { get; set; }
        public decimal?   StockLendingFeeRate            { get; set; }
        public decimal?   StockLendingFeeMinimumAmount   { get; set; }
        public string?    AllowBorrowingFlag             { get; set; }
        public string?    StockBorrowingAccountID        { get; set; }
        public string?    StockBorrowingAccountFlag      { get; set; }
        public string?    InstrumentBorrowID             { get; set; }
        public string?    GatewaySendStatus              { get; set; }
        public string?    TradeRestrictionID             { get; set; }
        public string?    TradeRestrictionType           { get; set; }
        public string?    NewCustodianBankID             { get; set; }
        public string?    NewAccountID                   { get; set; }
        public decimal?   StopWithdrawalMultiplier       { get; set; }
        public decimal?   StopBuyingRatio                { get; set; }
        public decimal?   StockConcentrationRisk         { get; set; }
        public decimal?   MaintenanceDebtAssetRatio      { get; set; }
        public int?       ForceSellPeriod                { get; set; }
        public string?    ForceSellFlag                  { get; set; }
        public DateTime?  ForceSellDate                  { get; set; }
        public int?       ForceSellDays                  { get; set; }
        public decimal?   BuyFirstDepositLaterRatio      { get; set; }
        public decimal?   BuyFirstDepositLaterDiscountRa { get; set; }
        public decimal?   MarginRatio                    { get; set; }
        public string?    TPlusFlag                      { get; set; }
        public string?    BlackListFlag                  { get; set; }
        public string?    RegistrationType               { get; set; }
        public string?    AssetManagementClientID        { get; set; }
        public string?    CashCustodyFlag                { get; set; }
        public string?    StockCustodyFlag               { get; set; }
        public string?    ShareholderCode                { get; set; }
        public string?    OpenAccountWorkflowPartyID     { get; set; }
        public string?    OpenAccountWorkflowRemark      { get; set; }
        public string?    ParentAccountID                { get; set; }
        public string?    ParentAccountFlag              { get; set; }
        public string?    EncryptionPassword             { get; set; }
        public string?    bankacc                        { get; set; }
        public string?    bankcode                       { get; set; }
        public string?    citybank                       { get; set; }
        public decimal?   CashVCB                        { get; set; }
        public string?    TaxNumber                      { get; set; }
        public bool?      bIsProfessional                { get; set; }
        public string?    ProfessionalEffectiveType      { get; set; }
        public DateTime?  dProfessionalEffectiveFrom     { get; set; }
        public DateTime?  dProfessionalEffectiveTo       { get; set; }
        public string?    NameRep                        { get; set; }
        public DateTime?  dDateOfBirthRep                { get; set; }
        public string?    GenderRep                      { get; set; }
        public string?    PlaceOfBirthRep                { get; set; }
        public string?    IDNumberRep                    { get; set; }
        public string?    IDIssuePlaceRep                { get; set; }
        public DateTime?  dIDIssueDateRep                { get; set; }
        public string?    CountryIDRep                   { get; set; }
        public string?    PositionRep                    { get; set; }
        public string?    DesignationRep                 { get; set; }
        public string?    AddressRep                     { get; set; }
        public string?    SmsNumberRep                   { get; set; }
        public string?    EmailAddressRep                { get; set; }
        public DateTime?  TradeDate                      { get; set; }
        public string?    CreatedBy                      { get; set; }
        public DateTime   CreatedOn                      { get; set; }
        public string?    UpdatedBy                      { get; set; }
        public DateTime   UpdatedOn                      { get; set; }
        public string?    CheckedBy                      { get; set; }
        public DateTime?  CheckedOn                      { get; set; }
        public string?    IPAddress                      { get; set; }
        public bool       BondDepository                 { get; set; }
        public string?    AccountActivity                { get; set; }
        public string?    BusinessType                   { get; set; }
        public DateTime?  CreatedDateVSD                 { get; set; }
        public string?    errvsddesc                     { get; set; }
        public string?    Custatcom                      { get; set; }
    }
}
