namespace EBond_FO.Models
{
    public class IFG_Corporate_Bond_Info
    {
        public int id { get; set; }
        public string BeginString { get; set; }
        public string BodyLength { get; set; }
        public string MsgType { get; set; }
        public string SenderCompID { get; set; }
        public string SendingTime { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string MaISIN { get; set; }
        public string Tradingdate { get; set; }
        public string BoardCode { get; set; }
        public string SecurityTradingStatus { get; set; }
        public string TradingSessionID { get; set; }
        public string TradSesStatus { get; set; }
        public string MaturityDate { get; set; }
        public string INTEREST_RATE { get; set; }
        public string IssueDate { get; set; }
        public string BOND_PERIOD { get; set; }
        public string PERIOD_UNIT { get; set; }
        public string PERIOD_REMAIN { get; set; }
        public string INTEREST_TYPE { get; set; }
        public string INTEREST_PERIOD { get; set; }
        public string INTEREST_PERIOD_UNIT { get; set; }
        public string INTEREST_COUPON_TYPE { get; set; }
        public string INTERESTRATE_TYPE { get; set; }
        public string INTEREST_PAYMENT_TYPE { get; set; }
        public string Issuer { get; set; }
        public string TCPH { get; set; }
        public string Time { get; set; }
        public string TotalListingQtty { get; set; }
        public string DateNo { get; set; }
        public string BasicPrice { get; set; }
        public string FloorPice { get; set; }
        public string CeilingPice { get; set; }
        public string FloorPriceOut { get; set; }
        public string CeilingPriceOut { get; set; }
        public string FloorPriceRep { get; set; }
        public string CeilingPriceRep { get; set; }
        public string Parvalue { get; set; }
        public string MatchPrice { get; set; }
        public string MatchQtty { get; set; }
        public string OpenPrice { get; set; }
        public string ClosePice { get; set; }
        public string TotalVolumeTraded { get; set; }
        public string TotalValueTraded { get; set; }
        public string MidPx { get; set; }
        public string CurrentPrice { get; set; }
        public string CurrentQtty { get; set; }
        public string HighestPice { get; set; }
        public string LowestPrice { get; set; }
        public string NM_TotalTradedQtty { get; set; }
        public string NM_TotalTradedValue { get; set; }
        public string PT_MatchQtty { get; set; }
        public string PT_MatchPrice { get; set; }
        public string PT_MaxQtty { get; set; }
        public string PT_MaxPrice { get; set; }
        public string PT_MinQtty { get; set; }
        public string PT_MinPrice { get; set; }
        public string PT_TotalTradedQtty { get; set; }
        public string PT_TotalTradedValue { get; set; }
        public string Repos_TotalTradedQtty { get; set; }
        public string Repos_TotalTradedValue { get; set; }
        public string RemainForeignQtty { get; set; }
        public string PT_BestBidQtty { get; set; }
        public string PT_BestBidPrice { get; set; }
        public string PT_BestOfferQtty { get; set; }
        public string PT_BestOfferPrice { get; set; }
        public string PT_TotalBidQtty { get; set; }
        public string PT_TotalOfferQtty { get; set; }
        public string DTGDTP { get; set; }
        public string FOREIGN_RATE { get; set; }
        public string CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string IPAddress { get; set; }
    }
}
