namespace EBond_FO.Models
{
    public class IFG_Corporate_Bond_Info
    {
        public Int64 id { get; set; }
        public string? BeginString { get; set; }
        public int? BodyLength { get; set; }
        public string? MsgType { get; set; }
        public string? SenderCompID { get; set; }
        public string? SendingTime { get; set; }
        public string? Symbol { get; set; }
        public string? Name { get; set; }
        public string? MaISIN { get; set; }
        public string? Tradingdate { get; set; }
        public string? BoardCode { get; set; }
        public int? SecurityTradingStatus { get; set; }
        public string? TradingSessionID { get; set; }
        public int? TradSesStatus { get; set; }
        public DateTime? MaturityDate { get; set; }
        public double? INTEREST_RATE { get; set; }
        public DateTime? IssueDate { get; set; }
        public string? BOND_PERIOD { get; set; }
        public int? PERIOD_UNIT { get; set; }
        public int? PERIOD_REMAIN { get; set; }
        public int? INTEREST_TYPE { get; set; }
        public int? INTEREST_PERIOD { get; set; }
        public int? INTEREST_PERIOD_UNIT { get; set; }
        public int? INTEREST_COUPON_TYPE { get; set; }
        public int? INTERESTRATE_TYPE { get; set; }
        public int? INTEREST_PAYMENT_TYPE { get; set; }
        public string? Issuer { get; set; }
        public string? TCPH { get; set; }
        public string? Time { get; set; }
        public double? TotalListingQtty { get; set; }
        public string? DateNo { get; set; }
        public double? BasicPrice { get; set; }
        public double? FloorPice { get; set; }
        public double? CeilingPice { get; set; }
        public double? FloorPriceOut { get; set; }
        public double? CeilingPriceOut { get; set; }
        public double? FloorPriceRep { get; set; }
        public double? CeilingPriceRep { get; set; }
        public double? Parvalue { get; set; }
        public double? MatchPrice { get; set; }
        public double? MatchQtty { get; set; }
        public double? OpenPrice { get; set; }
        public double? ClosePice { get; set; }
        public double? TotalVolumeTraded { get; set; }
        public double? TotalValueTraded { get; set; }
        public double? MidPx { get; set; }
        public double? CurrentPrice { get; set; }
        public double? CurrentQtty { get; set; }
        public double? HighestPice { get; set; }
        public double? LowestPrice { get; set; }
        public double? NM_TotalTradedQtty { get; set; }
        public string? NM_TotalTradedValue { get; set; }
        public double? PT_MatchQtty { get; set; }
        public double? PT_MatchPrice { get; set; }
        public double? PT_MaxQtty { get; set; }
        public double? PT_MaxPrice { get; set; }
        public double? PT_MinQtty { get; set; }
        public double? PT_MinPrice { get; set; }
        public double? PT_TotalTradedQtty { get; set; }
        public double? PT_TotalTradedValue { get; set; }
        public double? Repos_TotalTradedQtty { get; set; }
        public double? Repos_TotalTradedValue { get; set; }
        public double? RemainForeignQtty { get; set; }
        public double? PT_BestBidQtty { get; set; }
        public double? PT_BestBidPrice { get; set; }
        public double? PT_BestOfferQtty { get; set; }
        public double? PT_BestOfferPrice { get; set; }
        public double? PT_TotalBidQtty { get; set; }
        public double? PT_TotalOfferQtty { get; set; }
        public string? DTGDTP { get; set; }
        public double? FOREIGN_RATE { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public string? IPAddress { get; set; }
    }
}
